// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo-beqcKZrQumcid5RRn7uQEKJIdLmfoY',
    appId: '1:6916386237:web:575a1ef0e908da929cf6d4',
    messagingSenderId: '6916386237',
    projectId: 'eyecg-b0f5c',
    authDomain: 'eyecg-b0f5c.firebaseapp.com',
    storageBucket: 'eyecg-b0f5c.appspot.com',
    measurementId: 'G-3VLRT3WWGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS2v6u18mi0FV-o6ljeAMw_BDx7ZPl54s',
    appId: '1:6916386237:android:f7af6443dd7562e09cf6d4',
    messagingSenderId: '6916386237',
    projectId: 'eyecg-b0f5c',
    storageBucket: 'eyecg-b0f5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBenjEy4qBEta7Gi68vorgUyorucus8R-I',
    appId: '1:6916386237:ios:7f37db767d796c599cf6d4',
    messagingSenderId: '6916386237',
    projectId: 'eyecg-b0f5c',
    storageBucket: 'eyecg-b0f5c.appspot.com',
    iosClientId: '6916386237-v588p2jdpgr13sogpaipu7mt8ruonj9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyecg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBenjEy4qBEta7Gi68vorgUyorucus8R-I',
    appId: '1:6916386237:ios:7f37db767d796c599cf6d4',
    messagingSenderId: '6916386237',
    projectId: 'eyecg-b0f5c',
    storageBucket: 'eyecg-b0f5c.appspot.com',
    iosClientId: '6916386237-v588p2jdpgr13sogpaipu7mt8ruonj9d.apps.googleusercontent.com',
    iosBundleId: 'com.example.eyecg',
  );
}
